#' Write crowdin.yml
#'
#' The `crowdin.yml` file should be placed in the root directory of the lesson.
#'
#' `crowdin.yml` is used by Crowdin for specifying how the translated lesson
#' files should be organized (amongst other Crowdin settings). `dovetail`
#' expects a certain file hierarchy for the translated lesson files, and the
#' `crowdin.yml` file generated by this function will make sure it is set up
#' correctly.
#'
#' @param lesson_dir Path to the lesson directory. Default: current working
#' directory.
#' @param overwrite Logical; if a `crowdin.yml` file already exists in
#' `lesson_dir`, should it be overwritten?
#'
#' @return The path to the newly written `crowdin.yml` file (invisibly).
#'  This is typically called for its side-effect of writing
#'  `crowdin.yml` to the lesson directory.
#' @export
use_crowdin_yml <- function(lesson_dir = ".", overwrite = NULL) {
  # checks
  assertthat::assert_that(assertthat::is.dir(lesson_dir))
  if (!is.null(overwrite)) {
    assertthat::assert_that(assertthat::is.flag(overwrite))
  }
  # body
  crowdin_yml_ext <- system.file("extdata", "crowdin.yml", package = "dovetail")
  crowdin_yml_lesson <- fs::path(lesson_dir, "crowdin.yml") |>
    fs::path_abs()
  crowdin_yml_exists <- fs::file_exists(crowdin_yml_lesson)
  if (crowdin_yml_exists && is.null(overwrite)) {
    cli::cli_alert_warning(
      "{.file {crowdin_yml_lesson}} already exists"
    )
    overwrite <- usethis::ui_yeah("Do you want to overwrite it?")
  }
  if (crowdin_yml_exists && !isTRUE(overwrite)) {
    cli::cli_abort(
      "{.file crowdin.yml} exists and `overwrite` is FALSE.")
    return(invisible())
  }
  res <- fs::file_copy(crowdin_yml_ext, lesson_dir, overwrite = TRUE) |>
    fs::path_abs()
  cli::cli_alert_success("{.file {crowdin_yml_lesson}} created")
  return(invisible(res))
}