# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "md_name", # <create_po_for_locale>
  "po_file", # <create_po_for_locale>
  ".", # <fix_yaml_header>
  ".", # <find_md_files>
  "md_path", # <find_md_files>
  "md_file", # <find_md_files>
  NULL
))
