#' Exclude pandoc fences from an MD file
#'
#' @param md_lines Character vector; lines read in from a markdown file
#'
#' @return Character vector with lines starting with ::: deleted
#' @autoglobal
#' @noRd
#'
exclude_fences <- function(md_lines) {
  # Early exit just returning input if no pandoc fences
  if (!any(stringr::str_detect(md_lines, "^\\:\\:\\:"))) {
    return(md_lines)
  }

  # Exclude pandoc fences
  fence_lines <- which(stringr::str_detect(md_lines, "^\\:\\:\\:"))

  if (length(fence_lines) > 0) {
    md_lines <- md_lines[-fence_lines]
  }

  md_lines

}

#' Exclude header from PO file
#' 
#' Only works if header was generated by po4a on default settings
#'
#' @param po_file Path to PO file
#'
#' @return Path to PO file with header deleted
#' @autoglobal
#' @noRd
#'
exclude_header <- function(po_file) {
  po_lines <- readr::read_lines(po_file)

  # Early exit just returning input if no pandoc fences
  if (!any(stringr::str_detect(po_lines, "SOME DESCRIPTIVE TITLE"))) {
    return(po_file)
  }

  # Exclude pandoc fences
  delete_start <- which(
    stringr::str_detect(po_lines, "SOME DESCRIPTIVE TITLE"))
  delete_end <- which(
    stringr::str_detect(po_lines, "Content-Transfer-Encoding"))
  delete_lines <- delete_start:delete_end

  if (length(delete_lines) > 0) {
    po_lines <- po_lines[-delete_lines]
    readr::write_lines(po_lines, po_file)
  }

  po_file

}

#' Generate a custom error message for {assertr}
#'
#' @param msg Message to print if there is an error
#' @return Stops function and prints error message
#' @noRd
err_msg <- function(msg) stop(msg, .call = FALSE)

#' Find all (R)md files in a folder
#'
#' @param search_path Folder to search for (R)md files
#'
#' @return Tibble
#' @autoglobal
#' @noRd
#'
find_md_files <- function(search_path = ".") {
  # List all md files, use this to format paths
  # for writing PO files
  tibble::tibble(
    md_path = list.files(
      path = search_path,
      pattern = "\\.md$|\\.Rmd$",
      ignore.case = TRUE,
      recursive = TRUE)
  ) %>%
    assertr::verify(
      nrow(.) > 0,
      error_fun = err_msg("No Rmd or md files found")
    ) %>%
    # Exclude any files the wrong folders
    dplyr::filter(
      !stringr::str_detect(md_path, "locale/|site/|po/|renv/")
    ) %>%
    # Format paths
    dplyr::mutate(
      md_file = fs::path_file(md_path),
      md_dir = fs::path_dir(md_path),
      md_name = fs::path_ext_remove(md_file)
    ) %>%
    assertr::assert(
      assertr::is_uniq, md_file,
      error_fun = err_msg("MD file names not unique")
    )
}
